import org.gradle.api.GradleException
import org.gradle.api.tasks.Sync
import org.gradle.api.tasks.bundling.Zip
import org.gradle.jvm.toolchain.JavaToolchainService
import java.io.File
import java.util.Locale

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.jackson.databind)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    applicationName = "Codex Chat Viewer"
    mainClass = "app.codexchatviewer.AppKt"
}

tasks.processResources {
    from("src/release/windows/app-icon-preview-256.png") {
        into("app/codexchatviewer")
        rename { "app-icon.png" }
    }
}

val appDisplayName = "Codex Chat Viewer"
val releaseArtifactName = "codex-chat-viewer-windows-x64.zip"
val packageInputDir = layout.buildDirectory.dir("jpackage/input")
val releaseOutputDir = layout.buildDirectory.dir("release/windows")
val appImageDir = releaseOutputDir.map { it.dir("app-image") }
val appImageRootDir = appImageDir.map { it.dir(appDisplayName) }
val windowsAppIcon = layout.projectDirectory.file("src/release/windows/app-icon.ico")
val windowsReleaseReadme = layout.projectDirectory.file("src/release/windows/README_FIRST_WINDOWS.txt")
val javaToolchains = extensions.getByType(JavaToolchainService::class)

fun candidateFile(path: String?): File? {
    if (path.isNullOrBlank()) {
        return null
    }

    val candidate = file(path)
    return candidate.takeIf(File::isFile)
}

fun candidateFromHome(path: String?): File? {
    if (path.isNullOrBlank()) {
        return null
    }

    val executableName = if (System.getProperty("os.name").lowercase(Locale.ROOT).contains("windows")) {
        "jpackage.exe"
    } else {
        "jpackage"
    }

    return file(path).resolve("bin").resolve(executableName).takeIf(File::isFile)
}

fun findJpackageOnPath(): File? {
    if (!System.getProperty("os.name").lowercase(Locale.ROOT).contains("windows")) {
        return null
    }

    val process = ProcessBuilder("where", "jpackage")
        .redirectErrorStream(true)
        .start()
    val output = process.inputStream.bufferedReader().use { it.readText() }
    if (process.waitFor() != 0) {
        return null
    }

    return output
        .lineSequence()
        .map(String::trim)
        .filter(String::isNotEmpty)
        .map(::File)
        .firstOrNull(File::isFile)
}

fun resolveJpackageExecutable(): File {
    val searchedLocations = linkedSetOf<String>()

    fun tryCandidate(description: String, candidate: File?): File? {
        searchedLocations += description
        return candidate?.takeIf(File::isFile)
    }

    val directCandidates = listOf(
        "Gradle property jpackageExecutable" to candidateFile(findProperty("jpackageExecutable") as String?),
        "JPACKAGE_EXECUTABLE environment variable" to candidateFile(System.getenv("JPACKAGE_EXECUTABLE")),
        "JPACKAGE_HOME environment variable" to candidateFromHome(System.getenv("JPACKAGE_HOME")),
        "JAVA_HOME environment variable" to candidateFromHome(System.getenv("JAVA_HOME")),
        "JDK_HOME environment variable" to candidateFromHome(System.getenv("JDK_HOME"))
    )

    directCandidates.forEach { (description, candidate) ->
        tryCandidate(description, candidate)?.let { return it }
    }

    val toolchainCandidate = runCatching {
        javaToolchains.launcherFor {
            languageVersion = JavaLanguageVersion.of(21)
        }.get().metadata.installationPath.file("bin/jpackage.exe").asFile
    }.getOrNull()
    tryCandidate("Gradle Java 21 toolchain", toolchainCandidate)?.let { return it }

    tryCandidate("where jpackage", findJpackageOnPath())?.let { return it }

    throw GradleException(
        buildString {
            appendLine("Unable to locate jpackage.")
            appendLine("Set JPACKAGE_HOME or JPACKAGE_EXECUTABLE, or pass -PjpackageExecutable=<full-path-to-jpackage>.")
            appendLine("Searched:")
            searchedLocations.forEach { location ->
                appendLine(" - $location")
            }
        }
    )
}

val prepareJpackageInput by tasks.registering(Sync::class) {
    group = "distribution"
    description = "Copies the application jar and runtime dependencies into the jpackage input directory."

    dependsOn(tasks.named("jar"))

    into(packageInputDir)
    from(tasks.named<Jar>("jar"))
    from(configurations.runtimeClasspath)
}

val createWindowsAppImage by tasks.registering(Exec::class) {
    group = "distribution"
    description = "Builds a Windows app-image with jpackage and a bundled runtime."
    notCompatibleWithConfigurationCache("jpackage executable discovery is resolved at task execution time.")

    dependsOn(prepareJpackageInput)
    inputs.dir(packageInputDir)
    inputs.file(windowsAppIcon)
    outputs.dir(appImageRootDir)

    doFirst {
        val jpackageExecutable = resolveJpackageExecutable()
        val outputDir = appImageDir.get().asFile
        val inputDir = packageInputDir.get().asFile
        val iconFile = windowsAppIcon.asFile
        val mainJar = tasks.named<Jar>("jar").get().archiveFileName.get()

        delete(outputDir)
        outputDir.mkdirs()

        commandLine(
            jpackageExecutable.absolutePath,
            "--type", "app-image",
            "--name", appDisplayName,
            "--input", inputDir.absolutePath,
            "--dest", outputDir.absolutePath,
            "--main-jar", mainJar,
            "--main-class", application.mainClass.get(),
            "--icon", iconFile.absolutePath
        )
    }
}

tasks.register<Zip>("packageWindowsReleaseZip") {
    group = "distribution"
    description = "Builds the Windows app-image and zips it for manual GitHub Releases upload."

    dependsOn(createWindowsAppImage)
    isPreserveFileTimestamps = true
    from(appImageRootDir) {
        into(appDisplayName)
    }
    from(windowsReleaseReadme) {
        into(appDisplayName)
    }
    destinationDirectory = releaseOutputDir
    archiveFileName = releaseArtifactName
}
